  [[main]]
  name = "Bio"
  weight = 50
  identifier = "bio"
  url = "/"

  [[main]]
  name = "Resume"
  weight = 75
  identifier = "resume"
  url = "https://www.dropbox.com/scl/fi/aifg9jgg86pj2fbx2quv5/Steven_Rashin_DS_Jan_24.pdf?rlkey=1bhnjbhbib7rtlplmaoqryn43&dl=0"

  [[main]]
  name = "Research"
  weight = 100
  identifier = "research"
  url = "/research/"

  [[main]]
  name = "Teaching"
  weight = 200
  identifier = "teaching"
  url = "/teaching/"
  #parent = "Teaching"  
  
  [[main]]
  name = "Software"
  weight = 300
  identifier = "software"
  url = "/software/"
  #parent = "software"

  [[main]]
  name = "Posts/Tutorials"
  weight = 400
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

