  [[main]]
  name = "Bio"
  weight = 50
  identifier = "bio"
  url = "/"

  [[main]]
  name = "Research"
  weight = 100
  identifier = "research"
  url = "/research/"

  [[main]]
  name = "Teaching"
  weight = 200
  identifier = "teaching"
  url = "/teaching/"
  #parent = "Teaching"  
  
  [[main]]
  name = "Software"
  weight = 300
  identifier = "software"
  url = "/software/"
  #parent = "software"

  [[main]]
  name = "Posts/Tutorials"
  weight = 400
  identifier = "posts"
  url = "/post/"


  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

